[workspace]
resolver = "2"
members = [
  "algo_registry",
  "vault",
  "algo_history",
  "creator_vault_factory",
  "creator_vault",
]

[workspace.dependencies]
soroban-sdk = { version = "21.6.0" }

[profile.release]
overflow-checks = true
